NCBC-2415: error CS0649 - Field 'SubDocSingularBase<T>.CurrentSpec' is null
Motivation
----------
Fixes a bug where possible null violation triggers a compiler error in
Jenkins. Note the actual code is not used as only Multi Sub-Document
commands are supported.

Change-Id: I1872968915ed3352f8f3e3f6895718b14ca5b5ac
Reviewed-on: http://review.couchbase.org/123792
Reviewed-by: David Nault <david.nault@couchbase.com>
Tested-by: Build Bot <build@couchbase.com>