NCBC-1865: Error CS0579: Duplicate attributes
Motivation
----------
Having attributes defined in both Couchbase.csproj and AssemblyInfo.cs
causes an CS0579 duplicate attribute error.

Modifications
-------------
 - Remove AssemblyCopyrightAttribute and AssemblyDescriptionAttribute
 from AssemblyInfo.cs - they are defined in Couchbase.csproj already and
 cause a conflict.

Result
------
CS5079 error is no longer triggered.

Change-Id: Iae53e2e48cd0224e8352dabb18d3772380d0541d
Reviewed-on: http://review.couchbase.org/106091
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Matt Ingenthron <ingenthr@gmail.com>