NCBC-917: Collection modified error during bulk operation
Motivation
----------
Fixes a bug were seperate thread would modify a collection while it was
being enumerated.

Modification
------------
Extended the critical section to include the check to see if the endpoints
collection was null or empty before loading it.

Result
-------
The code should no longer throw the following exception:
System.InvalidOperationException: Collection was modified; enumeration
operation may not execute.

Change-Id: I86b82c3d46f3c2f308f2ec1e77e184464aa1621e
Reviewed-on: http://review.couchbase.org/52349
Tested-by: Jeffry Morris <jeffrymorris@gmail.com>
Reviewed-by: Simon Baslé <simon@couchbase.com>